### PR TITLE
Fix check access of nested fields of object

### LINKED ISSUE #297: Type checker does not recursively check assign
### How to Reproduce

```
class Y(def a: Float)

class X
    def y: Y
    def init(self, a: Float) =>
         self.y := Y(a)

def x := X(10)

x.y.a := x.y.a + 2
x.y.a := x.y.a - 3
x.y.a := x.y.a * 6

x.y.a := x.y.a / 7
x.y.a := x.y.a ^ 2

x.y.a := x.y.a << 10
```

Gives an error that the type checker does not recognize `x.y.a`

### Expected behavior

It should treat `x.y.a` as a `Float` in the above example.

Likely need to add more generation logic to fully check the above expression.

### PR DESCRIPTION
**Pull request by JSAbrahams**
### Relevant issues

- Closes #297 

### Summary

Fix #297 by recursively for each inner call also generating a constraint.

#### An example

`x.y.z` is turned into:
- `'x'.y == 'x.y'`
- `'x.y'.z == 'x.y.z'`

Then in the unifcation stage:
- `'x'.y` is a direct access so one can take the class of `x`, look at field `y`, and determine the of expression `'x.y'`.
- One now knows what `'x.y'` is in `'x.y'.z`, so we lookup `z` in whatever type `'x.y'` is to know the type of `x.y.z`.

### Added Tests
- Operations on nested access
- Print of nested access

### CODE REVIEW

File: tests/system/valid/class.rs [hunk 1]
```diff
@@ -1,3 +1,5 @@
+use log::Level;
```
Comment (JSAbrahams) [inline tests/system/valid/class.rs:1]: Remove this

**Comment by JSAbrahams** [comment]
Perhaps we are missing a substitute rule for access somewhere, though that does seem unlikely.
Also, it would be nice if we can get rid of all duplicate constraints before going into the unification stage, also for a more succinct trace.
I've tried to check before adding but didn't work yet for some reason.

File: src/check/constrain/generate/call.rs [hunk 2]
```diff
@@ -206,88 +206,72 @@ fn call_parameters(
...
+        _ => return Err(vec![TypeErr::new(property.pos, "Expected property call")]),
+    };
+
+    let entire_call_as_ast: AST = instance.iter().rfold(property.clone(), |acc, ast| {
+        let (instance, property) = (Box::from(ast.clone()), Box::from(acc));
+        AST::new(ast.pos, Node::PropertyCall { instance, property })
+    });
+    let entire_call_as_ast = Expected::try_from((&entire_call_as_ast, &env.var_mappings))?;
+
+    let ast_without_access = if instance.len() == 1 {
```
Comment (JSAbrahams) [inline src/check/constrain/generate/call.rs:256]: Bit sad that we don't use a more elegant float but instead an ugly if statement.
But not sure there is another way to do this.

File: src/check/constrain/constraint/iterator.rs [hunk 3]
```diff
@@ -69,7 +69,7 @@ impl Constraints {
         if constraint.is_flag {
             // Can only reinsert constraint once
             let msg = format!(
-                "Cannot infer type. Expected a {}, was {}",
+                "Cannot infer type. Expected {}, was {}",
```
Comment (JSAbrahams) [inline src/check/constrain/constraint/iterator.rs:72]: Change these messages back to use `and_or_a`

File: src/check/constrain/generate/call.rs [hunk 4]
```diff
@@ -206,88 +206,72 @@ fn call_parameters(
...
-                            args: args_with_self,
-                        },
-                    )),
-                },
-            );
+            let (constr, _) = gen_vec(args, env, ctx, constr)?;
+            let args = vec![last_inst.clone()]
+                .iter()
+                .chain(args)
+                .map(|ast| Expected::try_from((ast, &env.var_mappings)))
```
Comment (JSAbrahams) [inline src/check/constrain/generate/call.rs:240]: This closure could perhaps be on a separate line above

File: src/check/constrain/generate/call.rs [hunk 5]
```diff
@@ -206,88 +206,72 @@ fn call_parameters(
...
+    let entire_call_as_ast: AST = instance.iter().rfold(property.clone(), |acc, ast| {
+        let (instance, property) = (Box::from(ast.clone()), Box::from(acc));
+        AST::new(ast.pos, Node::PropertyCall { instance, property })
+    });
+    let entire_call_as_ast = Expected::try_from((&entire_call_as_ast, &env.var_mappings))?;
+
+    let ast_without_access = if instance.len() == 1 {
+        last_inst.clone()
+    } else {
+        let last = instance.remove(instance.len() - 1);
```
Comment (JSAbrahams) [inline src/check/constrain/generate/call.rs:259]: Hm is there a situation where this could panic?

File: src/check/constrain/unify/expression/substitute.rs [hunk 6]
```diff
@@ -22,25 +22,23 @@ pub fn substitute(
...
         constraint_pos += 1;
         macro_rules! replace {
             ($left:expr, $new:expr) => {{
-                let pos =
-                    format!("({}={}) ", old_constr.left.pos, old_constr.right.pos);
                 let side = if $left { "l" } else { "r" };
                 trace!(
                     "{:width$} [subbed {}\\{} {}]  {}  =>  {}",
-                    pos,
+                    "",
```
Comment (JSAbrahams) [inline src/check/constrain/unify/expression/substitute.rs:35]: Surely we still want to print pos somehow?

File: src/check/constrain/unify/link.rs [hunk 7]
```diff
@@ -18,13 +18,12 @@ pub fn unify_link(constraints: &mut Constraints, ctx: &Context, total: usize) ->
...
         let (left, right) = (&constraint.left, &constraint.right);
 
-        let pos = format!("{}={} ", left.pos, right.pos);
         let count = if constraints.len() <= total { total - constraints.len() } else { 0 };
         let unify = format!("{}\\{}", count, total);
         let msg =
             if constraint.msg.is_empty() { String::new() } else { format!(" {}", constraint.msg) };
 
-        trace!("{:width$}[{}{}]  {}", pos, unify, msg, constraint, width = 27);
+        trace!("{:width$}[{}{}]  {}", "", unify, msg, constraint, width = 0);
```
Comment (JSAbrahams) [inline src/check/constrain/unify/link.rs:26]: Surely we still want to print pos somehow?

File: src/check/constrain/constraint/expected.rs [hunk 8]
```diff
@@ -128,7 +127,7 @@ impl Display for Expect {
                 Access { entity, name } => format!("{}.{}", entity.expect, name.expect),
                 Function { name, args } => format!("{}({})", name, comma_delm(args)),
                 Field { name } => name.clone(),
-                Type { name: ty } => format!("{}'{}'", an_or_a(ty), ty),
+                Type { name: ty } => format!("{}", ty),
```
Comment (JSAbrahams) [inline src/check/constrain/constraint/expected.rs:130]: This can be a separate PR

File: src/check/constrain/constraint/iterator.rs [hunk 9]
```diff
@@ -34,7 +34,7 @@ impl Constraints {
     pub fn push_ty(&mut self, pos: Position, name: &Name) {
         let name = self.finished.get(&pos).map_or(name.clone(), |s_name| s_name.union(name));
         if self.finished.insert(pos, name.clone()).is_none() {
-            trace!("{:width$}type at {}: {}", "", pos, name, width = 0);
+            trace!("{:width$} type: {}", pos, name, width = 27);
```
Comment (JSAbrahams) [inline src/check/constrain/constraint/iterator.rs:37]: This can be a separate PR

File: src/check/constrain/constraint/iterator.rs [hunk 10]
```diff
@@ -47,7 +47,7 @@ impl Constraints {
     /// Only used during unification stage.
     pub fn push(&mut self, msg: &str, left: &Expected, right: &Expected) {
         let constraint = Constraint::new(msg, left, right);
-        trace!("{:width$}[gen {}] {}", "", msg, constraint, width = 17);
+        trace!("{:width$}[gen {}] {}", "", msg, constraint, width = 2);
```
Comment (JSAbrahams) [inline src/check/constrain/constraint/iterator.rs:50]: This can be a separate PR

File: src/check/constrain/constraint/iterator.rs (hunk 3 above)
Comment (JSAbrahams) [reply src/check/constrain/constraint/iterator.rs:72]: This can be a separate PR

File: src/check/constrain/unify/expression/substitute.rs [hunk 11]
```diff
@@ -22,25 +22,23 @@ pub fn substitute(
     let mut substituted = Constraints::new();
     let mut constraint_pos = offset;
 
-    trace!("{:width$} [subbing {}\\{}]  {}  <=  {}", "", offset, total, old, new, width = 30);
+    trace!("{:width$} [subbing {}\\{}]  {}  <=  {}", "", offset, total, old, new, width = 10);
```
Comment (JSAbrahams) [inline src/check/constrain/unify/expression/substitute.rs:25]: This can be a separate PR

File: src/check/constrain/unify/expression/substitute.rs (hunk 6 above)
Comment (JSAbrahams) [reply src/check/constrain/unify/expression/substitute.rs:35]: This can be a separate PR

File: src/check/constrain/unify/link.rs (hunk 7 above)
Comment (JSAbrahams) [reply src/check/constrain/unify/link.rs:26]: This can be a separate PR

File: src/check/constrain/unify/link.rs [hunk 12]
```diff
@@ -74,7 +73,7 @@ pub fn unify_link(constraints: &mut Constraints, ctx: &Context, total: usize) ->
 pub fn reinsert(constr: &mut Constraints, constraint: &Constraint, total: usize) -> Unified {
     let pos = format!("({}={}) ", constraint.left.pos.start, constraint.right.pos.start);
     let count = format!("[reinserting {}\\{}] ", total - constr.len(), total);
-    trace!("{:width$}{}{}", pos, count, constraint, width = 17);
+    trace!("{:width$}{}{}", pos, count, constraint, width = 15);
```
Comment (JSAbrahams) [inline src/check/constrain/unify/link.rs:76]: This can be a separate PR

File: src/check/result.rs [hunk 13]
```diff
@@ -103,6 +103,9 @@ impl WithSource for TypeErr {
 impl Display for TypeErr {
     fn fmt(&self, f: &mut Formatter) -> fmt::Result {
         let path = self.path.clone().map_or(String::from("<unknown>"), |p| p.display().to_string());
+        // remove trailing slash
+        let path = path.strip_suffix(MAIN_SEPARATOR).unwrap_or(&path);
```
Comment (JSAbrahams) [inline src/check/result.rs:107]: This can be a separate PR

File: src/generate/result.rs [hunk 14]
```diff
@@ -55,10 +55,14 @@ impl WithSource for UnimplementedErr {
 
 impl Display for UnimplementedErr {
     fn fmt(&self, f: &mut Formatter) -> fmt::Result {
+        let path =
+            self.path.clone().map_or(String::from("<unknown>"), |path| path.display().to_string());
+        let path = path.strip_suffix(MAIN_SEPARATOR).unwrap_or(&path);
```
Comment (JSAbrahams) [inline src/generate/result.rs:60]: This can be a separate PR

File: src/parse/result.rs [hunk 15]
```diff
@@ -1,7 +1,7 @@
 use std::cmp::min;
 use std::fmt;
 use std::fmt::{Display, Formatter};
-use std::path::PathBuf;
+use std::path::{MAIN_SEPARATOR, PathBuf};
```
Comment (JSAbrahams) [inline src/parse/result.rs:4]: This can be a separate PR

File: src/parse/result.rs [hunk 16]
```diff
@@ -173,6 +173,9 @@ impl Display for ParseErr {
                 )
             });
 
+        let path =
+            self.path.clone().map_or(String::from("<unknown>"), |path| path.display().to_string());
+        let path = path.strip_suffix(MAIN_SEPARATOR).unwrap_or(&path);
```
Comment (JSAbrahams) [inline src/parse/result.rs:178]: This can be a separate PR
