### PR TITLE
WIP Desugar default constructor and parents arguments

### LINKED ISSUE #53: Operations are not parsed fully
### Description of Bug
Operations are only parsed in situations where it starts with literal or `self`. 

### How to Reproduce
Take for instance `self.other + 10`
This is parsed as a function call, and it does not parse the operation fully.

### Expected behaviour
We would expect that any expression followed by a known operator should be parsed as an operation, with the correct order of operations.

### Additional context
...

### LINKED ISSUE #105: Desugar default constructors to init functions
### Current Issue
Default constructors are ignored.

### Description of the feature
Default constructors are constructors stored alongside the class name, i.e.: 
```mamba
class MyServer(mut self: DisconnectedMyServer, def ip_address: IPv4Address) isa Server
```

The above should be desugared such that we have an init function where these are assigned to self. So the above is roughly desugared to (self should be ignored):
```python
class MyServer(Server):
    ip_address = None

    __init__(self, ip_address):
        self.ip_address = ip_address
```

### Description of potential solution
We desugar class nodes such that:
- The class gets the constructor arguments as properties (save for `self`).
- The class assign the constructor arguments to the properties of `self`.

The type checker should that that there is no other `init` function in the class.

### PR DESCRIPTION
**Pull request by JSAbrahams**
### Relevant issues
Fixes #105 
Fixes #53 
Addresses #19 

### Summary
- Move assignment outside `try` `except` for `handle` statements following an assign.
- Preserve type definitions, these become classes with empty methods in Python, which is the Python equivalent of an interface.
- Fix #53 by only parsing a single expression for postfix calls
- #19 is somewhat addressed by making property accesses with nothing following them property access. If we add brackets (with or without arguments), these do become functions. So the syntax behaves the same was as in Python.
  The intent was to someday allow users to call functions without brackets if these don't take arguments. So if we opt to still include this feature it will probably be included in V0.2

### CODE REVIEW

File: src/desugar/class.rs [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+use std::ops::Deref;
+
+/// Desugar a class.
+///
+/// If a class has inline arguments (arguments next to class), then we create a
+/// constructor and assume that there is no constructor in the body of a class.
+/// This property should be ensured by the type checker.
+///
+/// We add arguments and calls to super for parents.
+pub fn desugar_class(node: &ASTNode, ctx: &Context, state: &State) -> Core {
```
Comment (JSAbrahams) [inline src/desugar/class.rs]: This is the important part of this PR.
The application logic for desugaring both inline constructors and calls to parent is somewhat convoluted at the moment. I'm lookinto ways to simplify this.
I could probably split this into two major passes, one to check what has to be built, and a second one that actually builds the relevant nodes.
As it is now, these two stages are a bit intertwined (though this is also somewhat necessary as we want to desugar default and literal arguments as well).

**Comment by JSAbrahams** [comment]
Probably best to only merge this after #123 so we can verify the output.
